### PR TITLE
arm64: dts: qcom: msm8916-samsung-e5: Add display panel

### PR DESCRIPTION
**Pull request by wonderfulShrineMaidenOfParadise**

### CODE REVIEW

**Comment by stephan-gh** [comment]
@wonderfulShrineMaidenOfParadise Can you send `arm64: dts: qcom: msm8916-samsung-e5: Add touchscreen` upstream if it was tested by someone successfully?

**Comment by wonderfulShrineMaidenOfParadise** [comment]
Link: https://lore.kernel.org/lkml/20230730025315.8579-1-linmengbo0689@protonmail.com/

**Comment by stephan-gh** [comment]
I added the touchscreen patch to `wip/msm8916/6.5-rc4`. The display commit looks fine except for one tiny detail.  As far as I can tell

- A5 has the EA8061V_AMS497EE***01*** panel
- E5 has the EA8061V_AMS497EE***10*** panel

Those are very similar but there are still some subtle differences. It seems to be mostly related to the brightness stuff:

<details>

<summary>Click me for a diff between the panel DTs!</summary>

```diff
diff --git a/EA8061V_AMS497EE01/dsi_panel_EA8061V_AMS497EE01_HD_octa_video.dtsi b/EA8061V_AMS497EE10/dsi_panel_EA8061V_AMS497EE10_HD_octa_video.dtsi
index 25bda58f492..489b1108656 100755
--- a/EA8061V_AMS497EE01/dsi_panel_EA8061V_AMS497EE01_HD_octa_video.dtsi
+++ b/EA8061V_AMS497EE10/dsi_panel_EA8061V_AMS497EE10_HD_octa_video.dtsi
@@ -18,8 +18,8 @@
 
  */
 &mdss_mdp {
-	dsi_ea8061_video_hd: ss_dsi_panel_EA8061V_AMS497EE01_HD {
-		qcom,mdss-dsi-panel-name = "ss_dsi_panel_EA8061V_AMS497EE01_HD";
+	ss_dsi_panel_EA8061V_AMS497EE10_HD: ss_dsi_panel_EA8061V_AMS497EE10_HD {
+		qcom,mdss-dsi-panel-name = "ss_dsi_panel_EA8061V_AMS497EE10_HD";
 
 		qcom,mdss-dsi-panel-controller = <&mdss_dsi0>;
 
@@ -28,7 +28,7 @@
 		qcom,mdss-dsi-bpp = <24>;
 		qcom,mdss-dsi-panel-destination = "display_1";
 
-		qcom,mdss-dsi-panel-timings = [36 23 14 00 42 46 18 30 26 03 04 00];
+		qcom,mdss-dsi-panel-timings = [36 23 14 00 42 46 18 40 26 03 04 00];
 
 		qcom,mdss-dsi-on-command = [
 			39 00 00 00 00 00 03 F0 5a 5a
@@ -135,6 +135,10 @@
  *
  * ************************************************************************************************************************************
  */
+/*		samsung,dsi-lp11-init;*/
+		samsung,esc-clk-128M;
+		samsung,outdoor_mode_support;
+
 		samsung,mdss-power-on-reset-delay-us = <5000>;
 		samsung,mdss-dsi-off-reset-delay-us = <1000>;
 
@@ -168,14 +172,14 @@
 		samsung,manufacture_id1_rx_cmds_revA = [ 06 01 00 00 00 00 01 db 01 00];
 		samsung,manufacture_id2_rx_cmds_revA = [ 06 01 00 00 00 00 01 dc 01 00];
 
-		samsung,manufacture_date_rx_cmds_revA = [ 06 01 00 00 00 00 01 C8 02 28];	/* read B6 24~25th , 23=0x17*/
+		samsung,manufacture_date_rx_cmds_revA = [ 06 01 00 00 00 00 01 C8 02 28];	/* read C8 24~25th , 23=0x17*/
 		samsung,ddi_id_rx_cmds_revA = [ 06 01 00 00 00 00 01 d6 05 00];	/* read D6 1~5th */
 		samsung,mtp_read_sysfs_rx_cmds_revA = [ 06 01 00 00 00 00 01 01 01 01];
 
-		samsung,hbm_rx_cmds_revA = [ 06 01 00 00 00 00 01 C8 06 21];	/* read C8 34~39th , 33=0x21 */
+		samsung,hbm_rx_cmds_revA = [ 06 01 00 00 00 00 01 C8 07 21];	/* read C8 34~40th , 33=0x21 */
 		samsung,hbm2_rx_cmds_revA = [ 06 01 00 00 00 00 01 C8 0F 2A];	/* read C8 43~57th , 42=0x2A */
 
-		samsung,elvss_rx_cmds_revA = [ 06 01 00 00 00 00 01 C8 01 27];	/* read C8 40th , 39=0x27*/
+		samsung,elvss_rx_cmds_revA = [ 06 01 00 00 00 00 01 B6 01 03];
 		samsung,mdnie_read_rx_cmds_revA = [ 06 01 00 00 00 00 01 A1 04 00];
 
 		samsung,ldi_debug0_rx_cmds_revA = [06 01 00 00 00 00 01 0A 01 00];
@@ -193,6 +197,8 @@
 			39 00 00 00 00 00 03 B6 4C 8a
 			/* CAPS Setting */
 			39 00 00 00 00 00 02 B5 29
+			39 00 00 00 00 00 02 B0 03
+			39 00 00 00 00 00 02 B6 00
 		];	/* Low Temperature Command */
 
 		samsung,elvss_lowtemp2_tx_cmds_revA = [
@@ -257,48 +263,49 @@
 		* ************************************************************************************************************************
 		*/
 		samsung,aid_tx_cmds_revA = [
-			39 00 00 00 00 00 05	B2 00 00 04 DF	/* 0 samsung_brightness_aor_95p63 */
-			39 00 00 00 00 00 05	B2 00 00 04 D3	/* 1 samsung_brightness_aor_94p71 */
-			39 00 00 00 00 00 05	B2 00 00 04 C7	/* 2 samsung_brightness_aor_93p79 */
-			39 00 00 00 00 00 05	B2 00 00 04 BB	/* 3 samsung_brightness_aor_92p87 */
-			39 00 00 00 00 00 05	B2 00 00 04 B0	/* 4 samsung_brightness_aor_92p02 */
-			39 00 00 00 00 00 05	B2 00 00 04 A4	/* 5 samsung_brightness_aor_91p10 */
-			39 00 00 00 00 00 05	B2 00 00 04 99	/* 6 samsung_brightness_aor_90p26 */
-			39 00 00 00 00 00 05	B2 00 00 04 8D	/* 7 samsung_brightness_aor_89p34 */
-			39 00 00 00 00 00 05	B2 00 00 04 82	/* 8 samsung_brightness_aor_88p50 */
-			39 00 00 00 00 00 05	B2 00 00 04 76	/* 9 samsung_brightness_aor_87p58 */
-			39 00 00 00 00 00 05	B2 00 00 04 6A	/* 10 samsung_brightness_aor_86p66 */
-			39 00 00 00 00 00 05	B2 00 00 04 5F	/* 11 samsung_brightness_aor_85p81 */
-			39 00 00 00 00 00 05	B2 00 00 04 52	/* 12 samsung_brightness_aor_84p82 */
-			39 00 00 00 00 00 05	B2 00 00 04 3B	/* 13 samsung_brightness_aor_83p05 */
-			39 00 00 00 00 00 05	B2 00 00 04 31	/* 14 samsung_brightness_aor_82p29 */
-			39 00 00 00 00 00 05	B2 00 00 04 25	/* 15 samsung_brightness_aor_81p37 */
-			39 00 00 00 00 00 05	B2 00 00 04 18	/* 16 samsung_brightness_aor_80p37 */
-			39 00 00 00 00 00 05	B2 00 00 04 01	/* 17 samsung_brightness_aor_78p60 */
-			39 00 00 00 00 00 05	B2 00 00 03 F5	/* 18 samsung_brightness_aor_77p68 */
-			39 00 00 00 00 00 05	B2 00 00 03 DB	/* 19 samsung_brightness_aor_75p69 */
-			39 00 00 00 00 00 05	B2 00 00 03 C5	/* 20 samsung_brightness_aor_74p00 */
-			39 00 00 00 00 00 05	B2 00 00 03 B7	/* 21 samsung_brightness_aor_72p93 */
-			39 00 00 00 00 00 05	B2 00 00 03 9E	/* 22 samsung_brightness_aor_71p01 */
-			39 00 00 00 00 00 05	B2 00 00 03 88	/* 23 samsung_brightness_aor_69p33 */
-			39 00 00 00 00 00 05	B2 00 00 03 64	/* 24 samsung_brightness_aor_66p56 */
-			39 00 00 00 00 00 05	B2 00 00 03 4B	/* 25 samsung_brightness_aor_64p64 */
-			39 00 00 00 00 00 05	B2 00 00 03 32	/* 26 samsung_brightness_aor_62p73 */
-			39 00 00 00 00 00 05	B2 00 00 03 0D	/* 27 samsung_brightness_aor_59p89 */
-			39 00 00 00 00 00 05	B2 00 00 02 E7	/* 28 samsung_brightness_aor_56p98 */
-			39 00 00 00 00 00 05	B2 00 00 02 C2	/* 29 samsung_brightness_aor_54p14 */
-			39 00 00 00 00 00 05	B2 00 00 02 9D	/* 30 samsung_brightness_aor_51p30 */
-			39 00 00 00 00 00 05	B2 00 00 02 79	/* 31 samsung_brightness_aor_48p54 */
-			39 00 00 00 00 00 05	B2 00 00 02 45	/* 32 samsung_brightness_aor_44p56 */
-			39 00 00 00 00 00 05	B2 00 00 02 13	/* 33 samsung_brightness_aor_40p72 */
+			39 00 00 00 00 00 05	B2 00 00 04 E6	/* 0 samsung_brightness_aor_95p7 */
+			39 00 00 00 00 00 05	B2 00 00 04 DC	/* 1 samsung_brightness_aor_94p25 */
+			39 00 00 00 00 00 05	B2 00 00 04 D2	/* 2 samsung_brightness_aor_93p33 */
+			39 00 00 00 00 00 05	B2 00 00 04 C8	/* 3 samsung_brightness_aor_92p41 */
+			39 00 00 00 00 00 05	B2 00 00 04 BE	/* 4 samsung_brightness_aor_91p41 */
+			39 00 00 00 00 00 05	B2 00 00 04 B4	/* 5 samsung_brightness_aor_90p49 */
+			39 00 00 00 00 00 05	B2 00 00 04 AA	/* 6 samsung_brightness_aor_89p65 */
+			39 00 00 00 00 00 05	B2 00 00 04 A0	/* 7 samsung_brightness_aor_88p73 */
+			39 00 00 00 00 00 05	B2 00 00 04 96	/* 8 samsung_brightness_aor_87p88 */
+			39 00 00 00 00 00 05	B2 00 00 04 8A	/* 9 samsung_brightness_aor_87p04 */
+			39 00 00 00 00 00 05	B2 00 00 04 82	/* 10 samsung_brightness_aor_85p89 */
+			39 00 00 00 00 00 05	B2 00 00 04 76	/* 11 samsung_brightness_aor_84p97 */
+			39 00 00 00 00 00 05	B2 00 00 04 6C	/* 12 samsung_brightness_aor_84p05 */
+			39 00 00 00 00 00 05	B2 00 00 04 57	/* 13 samsung_brightness_aor_82p21 */
+			39 00 00 00 00 00 05	B2 00 00 04 4C	/* 14 samsung_brightness_aor_81p21 */
+			39 00 00 00 00 00 05	B2 00 00 04 40	/* 15 samsung_brightness_aor_80p83 */
+			39 00 00 00 00 00 05	B2 00 00 04 32	/* 16 samsung_brightness_aor_80p29 */
+			39 00 00 00 00 00 05	B2 00 00 04 18	/* 17 samsung_brightness_aor_77p61 */
+			39 00 00 00 00 00 05	B2 00 00 04 08	/* 18 samsung_brightness_aor_76p69 */
+			39 00 00 00 00 00 05	B2 00 00 03 EE	/* 19 samsung_brightness_aor_74p92 */
+			39 00 00 00 00 00 05	B2 00 00 03 D1	/* 20 samsung_brightness_aor_73p08 */
+			39 00 00 00 00 00 05	B2 00 00 03 B7	/* 21 samsung_brightness_aor_72p09 */
+			39 00 00 00 00 00 05	B2 00 00 03 9E	/* 22 samsung_brightness_aor_70p17 */
+			39 00 00 00 00 00 05	B2 00 00 03 88	/* 23 samsung_brightness_aor_68p25 */
+			39 00 00 00 00 00 05	B2 00 00 03 64	/* 24 samsung_brightness_aor_65p41 */
+			39 00 00 00 00 00 05	B2 00 00 03 4B	/* 25 samsung_brightness_aor_63p50 */
+			39 00 00 00 00 00 05	B2 00 00 03 32	/* 26 samsung_brightness_aor_61p58 */
+			39 00 00 00 00 00 05	B2 00 00 03 0D	/* 27 samsung_brightness_aor_58p82 */
+			39 00 00 00 00 00 05	B2 00 00 02 E7	/* 28 samsung_brightness_aor_53p22 */
+			39 00 00 00 00 00 05	B2 00 00 02 C2	/* 29 samsung_brightness_aor_50p38 */
+			39 00 00 00 00 00 05	B2 00 00 02 9D	/* 30 samsung_brightness_aor_47p62 */
+			39 00 00 00 00 00 05	B2 00 00 02 79	/* 31 samsung_brightness_aor_43p87 */
+			39 00 00 00 00 00 05	B2 00 00 02 45	/* 32 samsung_brightness_aor_40p11 */
+			39 00 00 00 00 00 05	B2 00 00 02 13	/* 33 samsung_brightness_aor_39p95 */
 			39 00 00 00 00 00 05	B2 00 00 01 E7	/* 34 samsung_brightness_aor_37p35 */
-			39 00 00 00 00 00 05	B2 00 00 01 AE	/* 35 samsung_brightness_aor_32p98 */
-			39 00 00 00 00 00 05	B2 00 00 01 76	/* 36 samsung_brightness_aor_28p68 */
-			39 00 00 00 00 00 05	B2 00 00 01 39	/* 37 samsung_brightness_aor_24p00 */
-			39 00 00 00 00 00 05	B2 00 00 00 F8	/* 38 samsung_brightness_aor_19p02 */
-			39 00 00 00 00 00 05	B2 00 00 00 B4	/* 39 samsung_brightness_aor_13p80 */
-			39 00 00 00 00 00 05	B2 00 00 00 63	/* 40 samsung_brightness_aor_7p59 */
-			39 00 00 00 00 00 05	B2 00 00 00 0A	/* 41 samsung_brightness_aor_0p77 */
+			39 00 00 00 00 00 05	B2 00 00 01 E7	/* 35 samsung_brightness_aor_32p29 */
+			39 00 00 00 00 00 05	B2 00 00 01 AE	/* 36 samsung_brightness_aor_27p99 */
+			39 00 00 00 00 00 05	B2 00 00 01 76	/* 37 samsung_brightness_aor_22p70 */
+			39 00 00 00 00 00 05	B2 00 00 01 39	/* 38 samsung_brightness_aor_17p33 */
+			39 00 00 00 00 00 05	B2 00 00 00 F8	/* 39 samsung_brightness_aor_11p66 */
+			39 00 00 00 00 00 05	B2 00 00 00 B4	/* 40 samsung_brightness_aor_11p66 */
+			39 00 00 00 00 00 05	B2 00 00 00 63	/* 41 samsung_brightness_aor_7p59 */
+			39 00 00 00 00 00 05	B2 00 00 00 0A	/* 42 samsung_brightness_aor_0p77 */
 		];
 
 		samsung,aid_map_table_revA = <
@@ -311,10 +318,10 @@
 			53	30		56	31		60	32		64	33		68	34
 			72	34		77	34		82	34		87	34		93	34
 			98	34		105	34		111	34		119	34		126	34
-			134	34		143	34		152	34		162	34		172	35
-			183	36		195	37		207	38		220	39		234	40
-			249	41		265	41		282	41		300	41		316	41
-			333	41		360	41
+			134	34		143	34		152	34		162	35		172	36
+			183	37		195	38		207	39		220	40		234	41
+			249	42		265	42		282	42		300	42		316	42
+			333	42		350	42		360	42
 		>;
 
 		/*
@@ -335,7 +342,7 @@
 			39 00 00 00 00 00 02 55 03 /* 3 */
 		];
 		samsung,acl_off_tx_cmds_revA = [
-			39 00 00 00 00 00 02 B5 29
+			39 00 00 00 00 00 02 B5 21
 			39 01 00 00 72 00 02 55 00
 			39 00 00 00 00 00 02 F7 01
 		];
@@ -352,7 +359,7 @@
 			134  2	143  2	152  2	162  2	172  2
 			183  2	195  2	207  2	220  2	234  2
 			249  2	265  2	282  2	300  2	316  2
-			333  2	360  2
+			333  2	350  2	360  2
 		>;
 		/*
 		 * ************************************************************************************************************************
@@ -360,24 +367,35 @@
 		 * ************************************************************************************************************************
 		 */
 		samsung,elvss_tx_cmds_revA = [
-			39 00 00 00 00 00 03 b6 5c 9B /* 0    82 ~ 2 nit : 0x9B */
-			39 00 00 00 00 00 03 b6 5c 9A /* 1    93 ~ 87 nit : 0x9A */
-			39 00 00 00 00 00 03 b6 5c 99 /* 2    105 ~ 98 nit : 0x99 */
-			39 00 00 00 00 00 03 b6 5c 98 /* 3    111 nit : 0x98 */
-			39 00 00 00 00 00 03 b6 5c 97 /* 4    126 ~ 119 nit : 0x97 */
-			39 00 00 00 00 00 03 b6 5c 96 /* 5    134 nit : 0x96 */
-			39 00 00 00 00 00 03 b6 5c 95 /* 6    143 nit : 0x95 */
-			39 00 00 00 00 00 03 b6 5c 94 /* 7    172 ~ 152 nit : 0x94 */
-			39 00 00 00 00 00 03 b6 5c 93 /* 8    183 nit : 0x93 */
-			39 00 00 00 00 00 03 b6 5c 92 /* 9    195 nit : 0x92 */
-			39 00 00 00 00 00 03 b6 5c 91 /* 10   207 nit : 0x91 */
-			39 00 00 00 00 00 03 b6 5c 90 /* 11   249 ~ 220 nit : 0x90 */
-			39 00 00 00 00 00 03 b6 5c 8F /* 12   265 nit : 0x8F */
-			39 00 00 00 00 00 03 b6 5c 8E /* 13   282 nit : 0x8E */
-			39 00 00 00 00 00 03 b6 5c 8D /* 14   300 nit : 0x8D */
-			39 00 00 00 00 00 03 b6 5c 8C /* 15   316 nit : 0x8C */
-			39 00 00 00 00 00 03 b6 5c 8B /* 16   333 nit : 0x8B */
-			39 00 00 00 00 00 03 b6 5c 8A /* 17   350 nit : 0x8A */
+			39 00 00 00 00 00 03 b6 4c 88 /* 0    5~20 nit : 0x88 */
+			39 00 00 00 00 00 03 b6 5c 8A /* 1    21 nit  : 0x8A */
+			39 00 00 00 00 00 03 b6 5c 8D /* 2    22 nit  : 0x8D */
+			39 00 00 00 00 00 03 b6 5c 90 /* 3    24 nit : 0x90 */
+			39 00 00 00 00 00 03 b6 5c 93 /* 4    25 nit : 0x93 */
+			39 00 00 00 00 00 03 b6 5c 96 /* 5    27 nit : 0x96 */
+			39 00 00 00 00 00 03 b6 5c 99 /* 6    29 nit : 0x99 */
+			39 00 00 00 00 00 03 b6 5c 9F /* 7    30~34 nit : 0x9F */
+			39 00 00 00 00 00 03 b6 5c 9E /* 8    37~47 nit : 0x9E */
+			39 00 00 00 00 00 03 b6 5c 9D /* 9    50~56 nit : 0x9D */
+			39 00 00 00 00 00 03 b6 5c 9C /* 10   60~68 nit : 0x9C */
+			39 00 00 00 00 00 03 b6 5c 9B /* 11   72~82 nit : 0x9B */
+			39 00 00 00 00 00 03 b6 5c 9A /* 14   93 ~ 87 nit : 0x9A */
+			39 00 00 00 00 00 03 b6 5c 99 /* 15   105 ~ 98 nit : 0x99 */
+			39 00 00 00 00 00 03 b6 5c 98 /* 16   111 nit : 0x98 */
+			39 00 00 00 00 00 03 b6 5c 97 /* 17   126 ~ 119 nit : 0x97 */
+			39 00 00 00 00 00 03 b6 5c 96 /* 18   134 nit : 0x96 */
+			39 00 00 00 00 00 03 b6 5c 95 /* 19   143 nit : 0x95 */
+			39 00 00 00 00 00 03 b6 5c 94 /* 20   172 ~ 152 nit : 0x94 */
+			39 00 00 00 00 00 03 b6 5c 93 /* 21   183 nit : 0x93 */
+			39 00 00 00 00 00 03 b6 5c 92 /* 22   195 nit : 0x92 */
+			39 00 00 00 00 00 03 b6 5c 91 /* 23   207 nit : 0x91 */
+			39 00 00 00 00 00 03 b6 5c 90 /* 24   249 ~ 220 nit : 0x90 */
+			39 00 00 00 00 00 03 b6 5c 8F /* 25   265 nit : 0x8F */
+			39 00 00 00 00 00 03 b6 5c 8E /* 26   282 nit : 0x8E */
+			39 00 00 00 00 00 03 b6 5c 8D /* 27   300 nit : 0x8D */
+			39 00 00 00 00 00 03 b6 5c 8C /* 28   316 nit : 0x8C */
+			39 00 00 00 00 00 03 b6 5c 8B /* 29   333 nit : 0x8B */
+			39 00 00 00 00 00 03 b6 5c 8A /* 30   350 nit : 0x8A */
 		];
 		/*
 		 * ************************************************************************************************************************
@@ -385,24 +403,35 @@
 		 * ************************************************************************************************************************
 		 */
 		samsung,smart_acl_elvss_tx_cmds_revA = [
-			39 00 00 00 00 00 03 b6 4c 9B /* 0    82 ~ 2 nit : 0x9B */
-			39 00 00 00 00 00 03 b6 4c 9A /* 1    93 ~ 87 nit : 0x9A */
-			39 00 00 00 00 00 03 b6 4c 99 /* 2    105 ~ 98 nit : 0x99 */
-			39 00 00 00 00 00 03 b6 4c 98 /* 3    111 nit : 0x98 */
-			39 00 00 00 00 00 03 b6 4c 97 /* 4    126 ~ 119 nit : 0x97 */
-			39 00 00 00 00 00 03 b6 4c 96 /* 5    134 nit : 0x96 */
-			39 00 00 00 00 00 03 b6 4c 95 /* 6    143 nit : 0x95 */
-			39 00 00 00 00 00 03 b6 4c 94 /* 7    172 ~ 152 nit : 0x94 */
-			39 00 00 00 00 00 03 b6 4c 93 /* 8    183 nit : 0x93 */
-			39 00 00 00 00 00 03 b6 4c 92 /* 9    195 nit : 0x92 */
-			39 00 00 00 00 00 03 b6 4c 91 /* 10   207 nit : 0x91 */
-			39 00 00 00 00 00 03 b6 4c 90 /* 11   249 ~ 220 nit : 0x90 */
-			39 00 00 00 00 00 03 b6 4c 8F /* 12   265 nit : 0x8F */
-			39 00 00 00 00 00 03 b6 4c 8E /* 13   282 nit : 0x8E */
-			39 00 00 00 00 00 03 b6 4c 8D /* 14   300 nit : 0x8D */
-			39 00 00 00 00 00 03 b6 4c 8C /* 15   316 nit : 0x8C */
-			39 00 00 00 00 00 03 b6 4c 8B /* 16   333 nit : 0x8B */
-			39 00 00 00 00 00 03 b6 4c 8A /* 17   350 nit : 0x8A */
+			39 00 00 00 00 00 03 b6 4c 88 /* 0    5~20 nit : 0x88 */
+			39 00 00 00 00 00 03 b6 4c 8A /* 1    21 nit  : 0x8A */
+			39 00 00 00 00 00 03 b6 4c 8D /* 2    22 nit  : 0x8D */
+			39 00 00 00 00 00 03 b6 4c 90 /* 3    24 nit : 0x90 */
+			39 00 00 00 00 00 03 b6 4c 93 /* 4    25 nit : 0x93 */
+			39 00 00 00 00 00 03 b6 4c 96 /* 5    27 nit : 0x96 */
+			39 00 00 00 00 00 03 b6 4c 99 /* 6    29 nit : 0x99 */
+			39 00 00 00 00 00 03 b6 4c 9F /* 7    30~34 nit : 0x9F */
+			39 00 00 00 00 00 03 b6 4c 9E /* 8    37~47 nit : 0x9E */
+			39 00 00 00 00 00 03 b6 4c 9D /* 9    50~56 nit : 0x9D */
+			39 00 00 00 00 00 03 b6 4c 9C /* 10   60~68 nit : 0x9C */
+			39 00 00 00 00 00 03 b6 4c 9B /* 11   72~82 nit : 0x9B */
+			39 00 00 00 00 00 03 b6 4c 9A /* 12   93 ~ 87 nit : 0x9A */
+			39 00 00 00 00 00 03 b6 4c 99 /* 13   105 ~ 98 nit : 0x99 */
+			39 00 00 00 00 00 03 b6 4c 98 /* 14   111 nit : 0x98 */
+			39 00 00 00 00 00 03 b6 4c 97 /* 15   126 ~ 119 nit : 0x97 */
+			39 00 00 00 00 00 03 b6 4c 96 /* 16   134 nit : 0x96 */
+			39 00 00 00 00 00 03 b6 4c 95 /* 17   143 nit : 0x95 */
+			39 00 00 00 00 00 03 b6 4c 94 /* 18   172 ~ 152 nit : 0x94 */
+			39 00 00 00 00 00 03 b6 4c 93 /* 19   183 nit : 0x93 */
+			39 00 00 00 00 00 03 b6 4c 92 /* 20   195 nit : 0x92 */
+			39 00 00 00 00 00 03 b6 4c 91 /* 21   207 nit : 0x91 */
+			39 00 00 00 00 00 03 b6 4c 90 /* 22   249 ~ 220 nit : 0x90 */
+			39 00 00 00 00 00 03 b6 4c 8F /* 23   265 nit : 0x8F */
+			39 00 00 00 00 00 03 b6 4c 8E /* 24   282 nit : 0x8E */
+			39 00 00 00 00 00 03 b6 4c 8D /* 25   300 nit : 0x8D */
+			39 00 00 00 00 00 03 b6 4c 8C /* 26   316 nit : 0x8C */
+			39 00 00 00 00 00 03 b6 4c 8B /* 27   333 nit : 0x8B */
+			39 00 00 00 00 00 03 b6 4c 8A /* 28   350 nit : 0x8A */
 		];
 
 		/* bl_level, Index in elvss command list */
@@ -410,16 +439,16 @@
 			5	0		6	0		7	0		8	0		9	0
 			10	0		11	0		12	0		13	0		14	0
 			15	0		16	0		17	0		19	0		20	0
-			21	0		22	0		24	0		25	0		27	0
-			29	0		30	0		32	0		34	0		37	0
-			39	0		41	0		44	0		47	0		50	0
-			53	0		56	0		60	0		64	0		68	0
-			72	0		77	0		82	0		87	1		93	1
-			98	2		105	2		111	3		119	4		126	4
-			134	5		143	6		152	7		162	7		172	7
-			183	8		195	9		207	10		220	11		234	11
-			249	11		265	12		282	13		300	14		316	15
-			333	16		360	17
+			21	1		22	2		24	3		25	4		27	5
+			29	6		30	7		32	7		34	7		37	8
+			39	8		41	8		44	8		47	8		50	9
+			53	9		56	9		60	10		64	10		68	10
+			72	11		77	11		82	11		87	12		93	12
+			98	13		105	13		111	14		119	15		126	15
+			134	16		143	17		152	18		162	18		172	18
+			183	19		195	20		207	21		220	22		234	22
+			249	22		265	23		282	24		300	25		316	26
+			333	27		350	28		360	28
 		>;
 
 		/*
@@ -505,7 +534,6 @@
 	mdss_dsi0: qcom,mdss_dsi@1a98000 {
 		gdsc-supply = <&gdsc_mdss>;
 		vdda-supply = <&pm8916_l2>;
-		vdd-supply = <&pm8916_l17>;
 		vddio-supply = <&pm8916_l6>;
 		qcom,platform-strength-ctrl = [ff 06];
 		qcom,platform-bist-ctrl = [00 00 b1 ff 00 00];
@@ -546,16 +574,6 @@
 			#address-cells = <1>;
 			#size-cells = <0>;
 
-/*
-			qcom,panel-supply-entry@0 {
-				reg = <0>;
-				qcom,supply-name = "vdd";
-				qcom,supply-min-voltage = <3000000>;
-				qcom,supply-max-voltage = <3000000>;
-				qcom,supply-enable-load = <100000>;
-				qcom,supply-disable-load = <100>;
-			};
-*/
 			qcom,panel-supply-entry@0 {
 				reg = <1>;
 				qcom,supply-name = "vddio";
```

</details>

@Grimler91 Perhaps you have an opinion if these differences are worth handling and how hard it would be with the brightness support in your PR? I still don't have a good understanding how the brightness stuff works.

**Comment by wonderfulShrineMaidenOfParadise** [comment]
Link: #200

**Comment by Grimler91** [comment]
Haven't looked into the vendor kernel code yet, but from dts differences above it seems like we could quite easily extend the ams497ee01 driver to be fully compatible with ams497ee10 as well, I'll look at doing that

**Comment by stephan-gh** [comment]
Can you generate a separate panel driver for e5 for now? I know it will probably end up being identical, but that way we can merge it independently even if the a5 one gets brightness support.

**Comment by wonderfulShrineMaidenOfParadise** [comment]
I would leave the display panel part for now. It would be great if a device owner continues with the works and actually tests it.

**Pull request closed without merging**
