### PR TITLE
Change memory information setting in devicetree

### PR DESCRIPTION
**Pull request by Boom-Hacker**

### CODE REVIEW

**Comment by stephan-gh** [comment]
Why? The bootloader (lk2nd) is responsible to fill out these nodes with the RAM size that is detected at runtime.

**Comment by Boom-Hacker** [comment]
it can't work,i tested,the 3GB devices is can't boot

**Comment by stephan-gh** [comment]
And with this booting works fine?

**Comment by Boom-Hacker** [comment]
yes

**Comment by stephan-gh** [comment]
Are you booting with lk2nd or directly from the stock bootloader?

**Pull request closed without merging**
