### PR TITLE
Add BAM DMUX driver as network interface to the modem

### PR DESCRIPTION
**Pull request by Minecrell**
This adds a new, (imo) mainline-quality driver for the BAM DMUX interface that provides the network interface to the modem on MSM8916 and MSM8974. It replaces the old 20k+ driver I ported from downstream a while ago.

I spent almost the entire last week to write it from scratch. It lacks some performance optimizations of the downstream driver but otherwise it has much better code quality. Overall it seems to work just fine. I have already tested it on:

- bq-paella
- samsung-a5ulte
- samsung-serranovelte

@TravMurav, @Sorixelle Would be great if you could give it a try on wileyfox-cracking/motorola-harpia.

I'm also looking for someone willing to test it on MSM8974. I'm hoping someone will volunteer :)

The instructions for using it are still largely the same, only the kernel config option is different. It's documented in this gist: https://gist.github.com/Minecrell/4cc2bfb9fcae18e294386b0a213907d1

### CODE REVIEW

**Comment by minlexx** [comment]
> I'm also looking for someone willing to test it on MSM8974. I'm hoping someone will volunteer :)

Of course. Hunderds of volunteers..

**Comment by z3ntu** [comment]
Missing dt bindings for remote`qcom,remote-power-collapse` ?

**Comment by Minecrell** [comment]
> Missing dt bindings for remote`qcom,remote-power-collapse` ?

Yes, I did not work on dt bindings at all yet :)

**Comment by z3ntu** [comment]
image
Works on 8974 :+1:

**Comment by craigcomstock** [comment]
On harpia with this kernel I was able to get ofono working for voice/sms. rmnet0 is present and I can do `dhcpcd rmnet0` and get an IP but no connectivity. In dmesg output I see a lot of `TX` messages but no `RX`.

I tried `ModemManager --debug` and `mmcli -L` and see no modems detected. Any ideas?
[mm.log](https://github.com/msm8916-mainline/linux/files/5268933/mm.log)

**Comment by Minecrell** [comment]
@craigcomstock 
> On harpia with this kernel I was able to get ofono working for voice/sms. rmnet0 is present and I can do dhcpcd rmnet0 and get an IP but no connectivity. In dmesg output I see a lot of TX messages but no RX.

You might need to set up the proper APN. @z3ntu wrote on Matrix:

> 20:40 <z3ntu> okay so `./remove-contexts; ./create-internet-context <apn>; ./activate-context 1` was the magic incantation

> I tried ModemManager --debug and mmcli -L and see no modems detected. Any ideas?

You need a special patched version of ModemManager from https://gitlab.com/Minecrell/pmaports/-/commits/modemmanager-rpmsg.

**Comment by craigcomstock** [comment]
> You need a special patched version of ModemManager from https://gitlab.com/Minecrell/pmaports/-/commits/modemmanager-rpmsg.

Actually. Maybe it failed due to ofono being activated. I rebooted and now mmcli -L returns a modem. So I will proceed with these tips as well. I do have the patched ModemManager.

**Comment by craigcomstock** [comment]
@Minecrell I pulled the firmware from my actual device "modem" partition and then things started working just fine using ModemManager. It definitely did not work with the default firmware in pmos or the firmware I had been using which worked for voice/sms with ofono: https://gitlab.com/unrznbl/vendor_motorola_harpia/-/tree/xt1607-retus-6.0.1. So good job and now I'll try and get MMS working.

Ofono works also. The crux was my firmware. :)

**Pull request merged**
