### PR TITLE
ARM: dts: qcom: msm8909: Add opp-table-cpu

### PR DESCRIPTION
**Pull request by wonderfulShrineMaidenOfParadise**

### CODE REVIEW

**Comment by stephan-gh** [comment]
I actually have changes to fully enable cpufreq on MSM8909 (up to 1.26 GHz), pushed them to `wip/msm8909/cpufreq`. Can you give those a try?

**Comment by wonderfulShrineMaidenOfParadise** [comment]
Yes, it works as expected.

**Comment by stephan-gh** [comment]
I'll try integrating my cpufreq changes during the upcoming 6.6 rebase, hopefully I can find the time to finish up the changes and submit them upstream until then. :)

**Comment by stephan-gh** [comment]
`msm8916/6.7-rc4` branch has full cpufreq for MSM8909 now :rocket:

**Pull request closed without merging**
