### PR TITLE
Add RT5033 charger device driver

### PR DESCRIPTION
**Pull request by msm8610**

### CODE REVIEW

**Comment by TravMurav** [comment]
Hi
I'm not sure what you are trying to achieve by importing this driver to our tree in it's current state. It at least has many styling problems and some obvious errors and is definitely not ready for this tree (not even talking about upstream).

Could you explain what you are trying to do?

**Comment by msm8610** [comment]
I want to add samsung galaxy grand prime to the project, before I add device trees I want add drivers for sensors. Source code for rt5033 charger I took from https://lkml.org/lkml/2015/1/9/34

**Comment by Minecrell** [comment]
> I want to add samsung galaxy grand prime to the project, before I add device trees I want add drivers for sensors. Source code for rt5033 charger I took from https://lkml.org/lkml/2015/1/9/34

Great, thanks for working on that device!

As far as I can tell, a variant of the Samsung Galaxy Grand Prime already exists in this tree (`msm8916-samsung-gprimeltecan.dts`) so I assume you will have some commits on top of that to add new features.

I would recommend starting with PRs for some simple device tree additions since those are easier to review. New drivers often take a significant time to review and finish up before we can merge it here (or it can be submitted upstream). Also, always submit the drivers together with the device tree additions (but as separate commits) so we can see where the driver is actually going to be used.

It would be great if you could join the postmarketOS mainline chat on IRC or Matrix so we can discuss this a bit more interactively, see https://wiki.postmarketos.org/wiki/Matrix_and_IRC

**Comment by msm8610** [comment]
To be more specific I'm working on gprimeltexx and fortuna variants. I checked how this file compiles and it turned out that include/linux/power_supply.h header is slightly different, basically as far as I know it's only naming changes. Thanks for your responses. I'll be in touch soon.

**Comment by Minecrell** [comment]
Hi @msm8610. As I suggested you should first try to get the device booting at all before you start working on new drivers. I will close this PR until then.

**Comment by wonderfulShrineMaidenOfParadise** [comment]
#323 is on the way. Please test if you are interested.

**Comment by wonderfulShrineMaidenOfParadise** [comment]
Also consider joining [#msm8916:postmarketos.org](https://app.element.io/#/room/#msm8916:postmarketos.org) for helps.

**Pull request closed without merging**
