### PR TITLE
arm64: dts: qcom: msm8916-acer-a1-724: Add notification LED

### PR DESCRIPTION
**Pull request by wonderfulShrineMaidenOfParadise**
Acer Iconia Talk S A1-724 uses KTD2026 LED driver. However, there is
no blue LED on it. Add it to the device tree.

### CODE REVIEW

**Comment by stephan-gh** [comment]
cc @a-andre

**Comment by stephan-gh** [comment]
Can you send `arm64: dts: qcom: msm8916-acer-a1-724: Add notification LED` upstream?

**Comment by wonderfulShrineMaidenOfParadise** [comment]
Link: https://lore.kernel.org/all/20231017125848.84311-1-raymondhackley@protonmail.com/

**Comment by stephan-gh** [comment]
Integrated into `msm8916/6.6-rc6`, thanks!

**Pull request closed without merging**
