### PR TITLE
oppo-a51f: add modem support

### PR DESCRIPTION
**Pull request by Hinokami-Kagura**

### CODE REVIEW

**Comment by Hinokami-Kagura** [comment]
From the downstream dts, the rmtfs_sharedmem used the following location, maybe need add in dts...
		qcom,rmtfs_sharedmem@8e580000 {
			compatible = "qcom,sharedmem-uio";
			reg = <0x86700000 0xe0000>;
			reg-names = "rmtfs";
			qcom,client-id = <0x01>;
		};

**Comment by Minecrell** [comment]
@Hinokami-Kagura That's the default location, defined in `msm8916.dtsi` in mainline.

More interesting perhaps would be

```
    ////TongJing.Shi@EXP.Modem, 2015.04.10, Modify for	
	/*#ifdef VENDOR_EDIT  //add for enlarge nv backup memory*/
	qcom,opponvbk_sharedmem@0x85f00000 {
		compatible = "qcom,sharedmem-uio";
		reg = <0x85f00000 0x100000>;
		reg-names = "opponvbk";
		qcom,client-id = <0x00000003>;
	};
    /*#endif  VENDOR_EDIT*/
```

but I don't know how to use this in mainline since it is separate from rmtfs.

**Comment by Minecrell** [comment]
I will close this temporarily in preparation of a rebase, let's re-open this once the modem is working properly.

**Comment by Hinokami-Kagura** [comment]
> @Hinokami-Kagura That's the default location, defined in `msm8916.dtsi` in mainline.
> 
> More interesting perhaps would be
> 
> ```
>     ////TongJing.Shi@EXP.Modem, 2015.04.10, Modify for	
> 	/*#ifdef VENDOR_EDIT  //add for enlarge nv backup memory*/
> 	qcom,opponvbk_sharedmem@0x85f00000 {
> 		compatible = "qcom,sharedmem-uio";
> 		reg = <0x85f00000 0x100000>;
> 		reg-names = "opponvbk";
> 		qcom,client-id = <0x00000003>;
> 	};
>     /*#endif  VENDOR_EDIT*/
> ```
> 
> but I don't know how to use this in mainline since it is separate from rmtfs.

AFAIK it's for Oppo internal usage, shouldn't see in custom ROM...

**Pull request closed without merging**
