### PR TITLE
arm64: dts: qcom: msm8916-motorola-osprey: initial bringup

### PR DESCRIPTION
**Pull request by MartijnBraam**
Mainly copied from the initial bringup of motorola-surnia since they are
quite similar devices.

Working:
* power/volume keys
* emmc/sd
* wifi
* usb
* vibrator

### CODE REVIEW

**Comment by Minecrell** [comment]
Did you test:

- SD card (enough to check if it shows up)
- Power button / volume down (maybe you did test these but those are not "gpio keys")
- Vibrator

Since those are also part of the changes here.

**Comment by MartijnBraam** [comment]
Yes, just tested the vibrator, it's all working.

**Review by Minecrell — APPROVED** [review]
Meh, CI is broken right now.

**Comment by Minecrell** [comment]
Thanks :)

**Pull request merged**
