### PR TITLE
idol347 headphones support with ak4375 driver

### PR DESCRIPTION
**Pull request by vknecht**
Current WIP status for idol347 headphones support and ak4375 driver.
Driver itself will need cleanup, and lpass fix commit will be replaced when @Minecrell submits it upstream.

### CODE REVIEW

**Comment by stephan-gh** [comment]
@vknecht Can you change this to UPSTREAM: (cherry-pick) the original commits from https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/log/ branch for-next. Perhaps keep the nice commit log in a separate branch for reference but this will make it easier to look at these changes.

**Comment by vknecht** [comment]
Just to be sure about how to proceed... Should I:
* drop initial "ASoC: Add AK4375 support" + all "SQUASHME ASoC:" commits (+ bindings)
* "replace" them with cherry-picked ones, editing them to add "UPSTREAM:" in front of first line
* effectively squash "arm64: dts: qcom: msm8916-alcatel-idol347" commits

What about the pin-switch related ones ? Also cherry-pick from Broonie's branch, or let you manage those elsewhere ?

**Comment by stephan-gh** [comment]
Basically yes. For the pin-switch stuff I'm still looking for volunteers to rewrite all the UCM configurations somehow so it can enable those if necessary... (Since in https://github.com/msm8916-mainline/linux/commits/asoc-pin-switches I also converted other devices to use it). :see_no_evil:

**Comment by stephan-gh** [comment]
Pushed to rebase4242, thanks!

**Pull request closed without merging**
